version: "3.8"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "8100:8200"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8000:8000

volumes:
  node_modules: