version: "3.8"
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8001:8000
    
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx.prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/www/:/var/www/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
# volumes: