# Stage 1 - the build process
FROM node:20 as build-deps
WORKDIR /app
RUN npm config set legacy-peer-deps true
RUN npm install -g @ionic/cli
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend ./
RUN npm run build --prod

# Stage 2 - the production environment
FROM nginx:1.17.9-alpine
COPY --from=build-deps /app/www /usr/share/nginx/html
COPY ./frontend/nginx_test.conf /etc/nginx/conf.d/default.conf