FROM python:3.7

COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /api

COPY ./backend/api /api/api
COPY ./backend/processed /api/processed

ENV PYTHONPATH=/api

EXPOSE 8000

ENTRYPOINT ["uvicorn"]
CMD ["api.main:app" , "--host", "0.0.0.0"]