on:
  push:
    branches:
      - main
name: docker_build_push_acr

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiledesk-backend -f ./deploy/Dockerfile_backend .
            docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiledesk-frontend -f ./deploy/Dockerfile_frontend .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiledesk-backend
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tiledesk-frontend