name: Trigger auto deployment for tiledesk-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tiledesk-app-AutoDeployTrigger-e23f9776-0f87-49e8-8363-b0a9103d99af.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TILEDESKAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tiledeskacr.azurecr.io
          registryUsername: ${{ secrets.TILEDESKAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TILEDESKAPP_REGISTRY_PASSWORD }}
          containerAppName: tiledesk-app
          resourceGroup: tiledesk
          imageToBuild: tiledeskacr.azurecr.io/tiledesk-app:${{ github.sha }}
          

     

